In [50]:
import pandas as pd

In [51]:
cov_hist_df = pd.read_csv("daily-covid-hist.csv", parse_dates=['date'])
oldest_df = cov_hist_df.replace('suppressed', 0)
older_df = oldest_df.replace(',','', regex=True)
older_df["cases_per_100K_7_day_count_change"] = pd.to_numeric(older_df["cases_per_100K_7_day_count_change"])
cov_hist_df["cases_per_100K_7_day_count_change"] = older_df["cases_per_100K_7_day_count_change"].values
cov_hist_df.rename(columns = {'fips_code':'county_fips'}, inplace = True)

In [52]:
cov_hist_df.sort_values(['county_fips', 'date'], inplace = True)
cov_hist_df["percent_change_7_day_rolling_mean"] = cov_hist_df.groupby('county_fips')["cases_per_100K_7_day_count_change"].pct_change().rolling(7).mean()*100

In [53]:
cov_hist_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1176030 entries, 533478 to 129469
Data columns (total 4 columns):
 #   Column                             Non-Null Count    Dtype
---  ------                             --------------    -----
 0   county_fips                        1176030 non-null  int64
 1   date                               1176030 non-null  datetime64[ns]
 2   cases_per_100K_7_day_count_change  1176030 non-null  float64
 3   percent_change_7_day_rolling_mean  787804 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(1)
memory usage: 44.9 MB

In [54]:
cov_hist_df.to_csv("clean_daily-covid-hist.csv")

In [55]:
cov_hist_df.head(50)

,county_fips,date,cases_per_100K_7_day_count_change,percent_change_7_day_rolling_mean
533478,1001,2021-04-01,98.445,NaN
680454,1001,2021-04-02,112.764,NaN
685843,1001,2021-04-03,98.445,NaN
827485,1001,2021-04-04,87.705,NaN
536713,1001,2021-04-05,76.966,NaN
829769,1001,2021-04-06,114.554,NaN
255560,1001,2021-04-07,153.932,NaN
132354,1001,2021-04-08,191.519,12.331858
540557,1001,2021-04-09,186.150,9.853493
1128862,1001,2021-04-10,175.410,10.843301
831825,1001,2021-04-11,186.150,13.276507
1133941,1001,2021-04-12,191.519,15.437749
837537,1001,2021-04-13,161.091,6.191339
686935,1001,2021-04-14,116.344,-2.687593
258417,1001,2021-04-15,82.335,-10.351784
840177,1001,2021-04-16,71.596,-11.814596
841505,1001,2021-04-17,80.546,-9.204561
133811,1001,2021-04-18,71.596,-11.666627
691646,1001,2021-04-19,64.436,-13.507312
846590,1001,2021-04-20,69.806,-10.047088
963203,1001,2021-04-21,94.865,-0.950584
1065,1001,2021-04-22,127.083,8.077040
263136,1001,2021-04-23,152.142,12.757278
966101,1001,2021-04-24,207.629,16.181540
969224,1001,2021-04-25,207.629,17.768920
264866,1001,2021-04-26,212.998,19.566980
694111,1001,2021-04-27,207.629,18.016333
403595,1001,2021-04-28,173.620,10.548082
970391,1001,2021-04-29,139.612,2.898146
849023,1001,2021-04-30,123.503,-1.567142
542041,1001,2021-05-01,55.487,-14.644696
545625,1001,2021-05-02,53.697,-15.105551
976048,1001,2021-05-03,50.117,-16.427394
853285,1001,2021-05-04,37.588,-19.638654
549784,1001,2021-05-05,42.958,-15.257772
136673,1001,2021-05-06,30.428,-16.626403
976453,1001,2021-05-07,25.059,-17.498764
141386,1001,2021-05-08,19.689,-12.692633
269919,1001,2021-05-09,19.689,-12.231778
272383,1001,2021-05-10,17.899,-12.578112
553774,1001,2021-05-11,28.638,-0.435645
980038,1001,2021-05-12,25.059,-4.261910
1136041,1001,2021-05-13,42.958,10.108869
698695,1001,2021-05-14,94.865,29.891285
406804,1001,2021-05-15,148.562,41.038859
412498,1001,2021-05-16,152.142,41.383112
702082,1001,2021-05-17,161.091,43.522166
275995,1001,2021-05-18,159.301,34.792317
554834,1001,2021-05-19,159.301,36.577657
6028,1001,2021-05-20,198.679,29.905059

In [44]:
import altair as alt
alt.__version__

'4.1.0'